# Copyright (C) 2026, Nicolas Scalese
# Licensed under the GNU GPL v3 or later. Info:  https://www.gnu.org/licenses/gpl-3.0.html


# --- HYPRIDLE configuration file ---

general {
    lock_cmd = pidof hyprlock || hyprlock                         # Command to launch the screen locker
    before_sleep_cmd = loginctl lock-session                      # Lock the session before the system goes to sleep
    after_sleep_cmd = hyprctl dispatch dpms on                    # Ensure the display turns back on after waking up
}

# Stage 1: Dim the screen (Power saving)
listener {
    timeout = 240                                                 # 4 minutes
    on-timeout = brightnessctl --save && brightnessctl set 5%     # Lower screen brightness to 10%
    on-resume = brightnessctl --restore                           # Restore brightness on activity
}

# Stage 2: Turn off the screen (DPMS)
listener {
    timeout = 260                                                 # 4 minutes, 20 seconds
    on-timeout = hyprctl dispatch dpms off                        # Turn off the monitor
    on-resume = hyprctl dispatch dpms on                          # Turn on the monitor
}

# Stage 3: Suspend the PC
listener {
    timeout = 360                                                 # 6 minutes
    on-timeout = systemctl suspend                                # Suspend to RAM
}
